### ISSUE TITLE
AttributeError: 'Categorical' object has no attribute 'levels'

### ISSUE THREAD

**Issue by sachinjm** [cauchyturing/Imaging-Time-Series-to-GAF-MTF-for-classifcation-using-Deep-Learning#3]
Getting error in line number 62 inside the serie21MTF.py file. 
line 62       return np.array(MSM), label, q.levels
AttributeError: 'Categorical' object has no attribute 'levels'

need to use this code for generating MTF. Please help me

**Comment by sachinjm** [comment]
resolved

**Comment by cauchyturing** [comment]
Thanks for asking, I would appreciate if you could share with us a little bit about how you resolved your problem.
